table.unpack = unpack
dofile("lua/callstacks.lua")
dofile("lua/command_track.lua")
dofile("lua/loadimage.lua")
dofile("lua/extra_ui.lua")
dofile("lua/battle_skip.lua")
dofile("lua/dialog_skip.lua")
start()
startCommandTrack()
startLoadImage()
startBattleSkip()
startDialogSkip()